{% set base_name = "libignition-fuel-tools" %}
{% set version = "4.0.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://bitbucket.org/ignitionrobotics/ign-fuel-tools/get/ignition-fuel-tools{{ major_version }}_{{ version }}.tar.gz
    sha256: 028cabc616e2b632ae9dde8e5f5d366f09414961bc5beabc637cdf28b8b04f27

build:
  number: 2
  skip: true  # [win and vc<14 or osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('c') }}    # [not win]
    - vs2017_win-64          # [win64]
    - vs2017_win-32          # [win32]
    - cmake
    - ninja
    - pkg-config             # [not win]
  host:
    - libignition-msgs5
    - libignition-common3
    - libcurl
    - jsoncpp
    - libzip
    - yaml
    - tinyxml2
    - libprotobuf >=3.11
  run:
    - libignition-msgs5
    - libignition-common3
    - libcurl
    - jsoncpp
    - libzip
    - yaml
    - tinyxml2
    - libprotobuf >=3.11

test:
  commands:
    - test -f ${PREFIX}/include/ignition/fuel_tools{{ major_version }}/ignition/fuel_tools.hh  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\fuel_tools{{ major_version }}\ignition\fuel_tools.hh (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/ignitionrobotics/ign-fuel-tools
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Ignition Fuel Tools is composed by a client library and command line tools for interacting with Ignition Fuel servers.'

extra:
  recipe-maintainers:
    - seanyen
