{% set base_name = "libignition-fuel-tools" %}
{% set version = "4.3.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-fuel-tools/archive/ignition-fuel-tools{{ major_version }}_{{ version }}.tar.gz
    sha256: 9f05c067a70059a22f46ccce37dcd02dd9fb7c9091608f61c8a0f4aee9b22a03
    patches:
      - fix_ignition_cmake_version.patch

build:
  number: 3
  skip: false
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config             # [not win]
  host:
    - libignition-msgs5
    - libignition-common3
    - libignition-tools1
    - libcurl
    - jsoncpp
    - libzip
    - yaml
    - tinyxml2
    - libprotobuf
  run:
    - libignition-msgs5
    - libignition-common3
    - libignition-tools1
    - libcurl
    - jsoncpp
    - libzip
    - yaml
    - tinyxml2
    - libprotobuf

test:
  commands:
    - test -f ${PREFIX}/include/ignition/fuel_tools{{ major_version }}/ignition/fuel_tools.hh  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\fuel_tools{{ major_version }}\ignition\fuel_tools.hh (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-fuel-tools
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Fuel Tools is composed by a client library and command line tools for interacting with Ignition Fuel servers.

extra:
  recipe-maintainers:
    - seanyen
    - Tobias-Fischer
    - traversaro
