{% set base_name = "libignition-fuel-tools" %}
{% set version = "4.6.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gazebosim/gz-fuel-tools/archive/ignition-fuel-tools{{ major_version }}_{{ version }}.tar.gz
    sha256: b28aa33003dc133f9bc08cdfeba592867cf14ef79a5ceef5f03310b3320e1062

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libignition-msgs5
    - libignition-math6
    - libignition-common3
    - libignition-tools1
    - libcurl
    - jsoncpp
    - libzip
    - yaml
    - tinyxml2
    - libprotobuf
    # Workaround for https://github.com/conda-forge/zlib-feedstock/issues/69#issuecomment-1577437024
    - zlib  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/fuel_tools{{ major_version }}/ignition/fuel_tools.hh  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\fuel_tools{{ major_version }}\ignition\fuel_tools.hh (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-fuel-tools
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Fuel Tools is composed by a client library and command line tools for interacting with Ignition Fuel servers.

extra:
  recipe-maintainers:
    - seanyen
    - Tobias-Fischer
    - traversaro
