{% set base_name = "libignition-fuel-tools" %}
{% set version = "4.2.1" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-fuel-tools/archive/ignition-fuel-tools{{ major_version }}_{{ version }}.tar.gz
    sha256: 447ee273d6c51577635ee9717d8e13d00273ee54d6d734d740510b129aa550df
    patches:
      - fix_ignition_cmake_version.patch

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('c') }}    # [not win]
    - vs2017_win-64          # [win64]
    - vs2017_win-32          # [win32]
    - cmake
    - ninja
    - pkg-config             # [not win]
  host:
    - libignition-msgs5
    - libignition-common3
    - libcurl
    - jsoncpp
    - libzip
    - yaml
    - tinyxml2
    - libprotobuf
  run:
    - libignition-msgs5
    - libignition-common3
    - libcurl
    - jsoncpp
    - libzip
    - yaml
    - tinyxml2
    - libprotobuf

test:
  commands:
    - test -f ${PREFIX}/include/ignition/fuel_tools{{ major_version }}/ignition/fuel_tools.hh  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\fuel_tools{{ major_version }}\ignition\fuel_tools.hh (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/ignitionrobotics/ign-fuel-tools
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Fuel Tools is composed by a client library and command line tools for interacting with Ignition Fuel servers.

extra:
  recipe-maintainers:
    - seanyen
    - Tobias-Fischer
